# Generated by Django 4.2.18 on 2025-02-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forum_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
