# Generated by Django 4.2.18 on 2025-01-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.TextField(),
        ),
    ]
