# Generated by Django 4.2.18 on 2025-02-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
